config/routes.rb
Rails.application.routes.draw do

  resources :specialists
  root 'orders#index'

  resources :orders
  resources :services
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/specialist.rb
class Specialist < ApplicationRecord
  belongs_to :order

  validates :name, presence: true
end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  before_action :set_specialist, only: %i[ show edit update destroy ]

  # GET /specialists or /specialists.json
  def index
    @specialists = Specialist.all
  end

  # GET /specialists/1 or /specialists/1.json
  def show
  end

  # GET /specialists/new
  def new
    @specialist = Specialist.new
  end

  # GET /specialists/1/edit
  def edit
  end

  # POST /specialists or /specialists.json
  def create
    @specialist = Specialist.new(specialist_params)

    respond_to do |format|
      if @specialist.save
        format.html { redirect_to specialist_url(@specialist), notice: "Specialist was successfully created." }
        format.json { render :show, status: :created, location: @specialist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialists/1 or /specialists/1.json
  def update
    respond_to do |format|
      if @specialist.update(specialist_params)
        format.html { redirect_to specialist_url(@specialist), notice: "Specialist was successfully updated." }
        format.json { render :show, status: :ok, location: @specialist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialists/1 or /specialists/1.json
  def destroy
    @specialist.destroy

    respond_to do |format|
      format.html { redirect_to specialists_url, notice: "Specialist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialist
      @specialist = Specialist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def specialist_params
      params.require(:specialist).permit(:name, :service)
    end
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/specialists/_form.html.erb
<%= form_with(model: specialist) do |form| %>
  <% if specialist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(specialist.errors.count, "error") %> prohibited this specialist from being saved:</h2>

      <ul>
        <% specialist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :service %>
    <%= form.text_field :service %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/specialists/edit.html.erb
<h1>Editing Specialist</h1>

<%= render 'form', specialist: @specialist %>

<%= link_to 'Show', @specialist %> |
<%= link_to 'Back', specialists_path %>

app/views/specialists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Specialists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialists.each do |specialist| %>
      <tr>
        <td><%= specialist.name %></td>
        <td><%= specialist.service %></td>
        <td><%= link_to 'Show', specialist %></td>
        <td><%= link_to 'Edit', edit_specialist_path(specialist) %></td>
        <td><%= link_to 'Destroy', specialist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specialist', new_specialist_path %>

app/views/specialists/new.html.erb
<h1>New Specialist</h1>

<%= render 'form', specialist: @specialist %>

<%= link_to 'Back', specialists_path %>

app/views/specialists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @specialist.name %>
</p>

<p>
  <strong>Service:</strong>
  <%= @specialist.service %>
</p>

<%= link_to 'Edit', edit_specialist_path(@specialist) %> |
<%= link_to 'Back', specialists_path %>